models.py
import sqlite3
from sqlite3 import Error

def init_db():
    try:
        conn = sqlite3.connect("app.db")
        cursor = conn.cursor()
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                email TEXT NOT NULL,
                password TEXT NOT NULL,
                image TEXT NOT NULL
            );
            """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS posts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                title TEXT NOT NULL,
                content TEXT NOT NULL,
                FOREIGN KEY (user_id) REFERENCES users (id)
            );
            """)
        conn.commit()
    except Error as e:
        print(e)

    conn.close()

def register_user(name, email, password, image):
    conn = sqlite3.connect("app.db")
    cursor = conn.cursor()
    cursor.execute("""
    INSERT INTO users (name, email, password, image)
    VALUES (?, ?, ?, ?);
    """, (name, email, password, image))
    conn.commit()
    conn.close()

def get_user(email, password):
    conn = sqlite3.connect("app.db")
    cursor = conn.cursor()
    cursor.execute("""
    SELECT * FROM users
    WHERE email = ? AND password = ?;
    """, (email, password))
    a=cursor.fetchone()
    conn.close()
    return a

def get_user_by_id(user_id):
    conn = sqlite3.connect("app.db")
    cursor = conn.cursor()
    cursor.execute("""
    SELECT * FROM users
    WHERE id = ?;
    """, (user_id,))
    a=cursor.fetchone()
    conn.close()
    return a

def get_posts_by_user_id(user_id):
    conn = sqlite3.connect("app.db")
    cursor = conn.cursor()
    cursor.execute("""
    SELECT * FROM posts
    WHERE user_id = ?;
    """, (user_id,))
    a=cursor.fetchall()
    conn.close()
    return a

def add_post(user_id, title, content):
    conn = sqlite3.connect("app.db")
    cursor = conn.cursor()
    cursor.execute("""
    INSERT INTO posts (user_id, title, content)
    VALUES (?, ?, ?);
    """, (user_id, title, content))
    conn.commit()
    conn.close()

controllers.py
from flask import Blueprint, render_template, redirect, url_for, request, session
import models, views
import os
from werkzeug.utils import secure_filename

bp = Blueprint("controller", __name__)

@bp.route("/")
def index():
    return redirect(url_for("controller.register"))

@bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        name = request.form["name"]
        email = request.form["email"]
        password = request.form["password"]
        image = request.files["image"]

        filename = secure_filename(image.filename)
        #image.save(os.path.join("/DOC/UC/SDP/static/uploads/", filename))
        #image.save(os.path.join("static/", filename))
        #image.save(os.path.join("static/", filename))
        image.save(os.path.join("socialMedia/static/", filename))
        models.register_user(name, email, password, filename)
        return redirect(url_for("controller.login"))
    return views.register()

@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        user = models.get_user(email, password)
        if user:
            session["user_id"] = user[0]
            return redirect(url_for("controller.profile"))
        else:
            return "Incorrect email or password. Please try again."
    return views.login()

@bp.route("/profile")
def profile():
    if "user_id" in session:
        user = models.get_user_by_id(session["user_id"])
        posts = models.get_posts_by_user_id(user[0])
        return render_template("profile.html", user=user, posts=posts)
    else:
        return redirect(url_for("controller.login"))

@bp.route("/logout")
def logout():
    session.pop("user_id", None)
    return views.login()

@bp.route('/submit_post', methods=['GET', 'POST'])
def submit_post():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        user_id = session['user_id']

        models.add_post(user_id, title, content)
        return redirect(url_for('controller.profile'))
    return views.submit_post()
    #return render_template('submit_post.html')

views.py
from flask import render_template

def register():
    return render_template("register.html")

def login():
    return render_template("login.html")

def profile(user, posts):
    return render_template("profile.html", user=user, posts=posts)

def submit_post():
    return render_template("submit_post.html")


templates/login.html
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <form action="{{ url_for('controller.login') }}" method="post">
            Email: <input type="email" name="email"><br>
            Password: <input type="password" name="password"><br>
            <input type="submit" value="Submit">
        </form>
    </body>
</html>

templates/output.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Data Science ISEG</title>
</head>
<body>

{% for table in tables %}
            {{titles[loop.index]}}
            {{ table|safe }}
{% endfor %}
</body>
</html>

templates/profile.html
<html>
    <head>
        <title>Profile</title>
    </head>
    <body>
        <h1>{{ user[1] }}</h1>
        <img src="/static/{{ user[4] }}" width="200" height="200" alt="{{ user[1] }}'s image">
        <h2>Posts:</h2>
        {% for post in posts %}
            <h3>{{ post[2] }}</h3>
            <p>{{ post[3] }}</p>
        {% endfor %}

        <a href="/submit_post">submit post</a>
    </body>
</html>

templates/register.html
<html>
    <head>
        <title>Register</title>
    </head>
    <body>
        <form action="{{ url_for('controller.register') }}" method="post" enctype="multipart/form-data">
            Name: <input type="text" name="name"><br>
            Email: <input type="email" name="email"><br>
            Password: <input type="password" name="password"><br>
            Image: <input type="file" name="image"><br>
            <input type="submit" value="Submit">
        </form>
        
    </body>
</html>

templates/submit_post.html
<html>
    <head>
        <title>Submit Post</title>
    </head>
    <body>
        <form action="{{ url_for('controller.submit_post') }}" method="post">
            Title: <input type="text" name="title"><br>
            Content: <textarea name="content"></textarea><br>
            <input type="submit" value="Submit">
        </form>
    </body>
</html>